# Generated by Django 2.1.1 on 2018-09-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20180901_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image_link',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
